[package]
name = "allocations"
version = "0.1.0"
edition = "2021"

[target.'cfg(unix)'.dependencies]
libc = "0.2.153"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.56.0", features = ["Win32_System", "Win32_System_Memory_NonVolatile"] }